#
#spring:
#  datasource:
#    url: jdbc:postgresql://10.20.30.40:5432/customer
#    username: HUSIH#72@y&n!*
#    password: hdsuiyfui9@*#c
#
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        globally_quoted_identifiers: true
#        format_sql: true
#    show-sql: true
#    database-platform: org.hibernate.dialect.posgreSQLDialect
#    generate-ddl: true
#
#  sql:
#     init:
#       mode: never
#       continue-on-error: false
#
#  main:
#    web-application-type: servlet
#
#  servlet:
#    multipart:
#      max-file-size: 20MB
#      max-request-size: 20MB
#
#  codec:
#    max-in-memory-size: 20MB
#
#
